{% set name = "git-absorb" %}
{% set version = "0.6.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tummychow/git-absorb/archive/{{ version }}.tar.gz
  sha256: 630e61a6edf1e244c38145bda98a522217c34d3ab70a3399af1f29f19e7ced26

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - git-absorb --help

about:
  home: https://github.com/tummychow/git-absorb
  license: BSD-3-Clause
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Automatic git commit --fixup
  dev_url: https://github.com/tummychow/git-absorb

extra:
  recipe-maintainers:
    - danielnachun
