context:
  version: "0.7.0"

package:
  name: git-absorb
  version: ${{ version }}

source:
  url: https://github.com/tummychow/git-absorb/archive/${{ version }}.tar.gz
  sha256: 65f5b80bcb726a0c40eeda94ccb47fce7f3fc4ed16021465196a37b907083eb8

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - git-absorb --help

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Automatic git commit --fixup
  homepage: https://github.com/tummychow/git-absorb
  repository: https://github.com/tummychow/git-absorb

extra:
  recipe-maintainers:
    - danielnachun
