context:
  version: "0.9.0"

package:
  name: git-absorb
  version: ${{ version }}

source:
  url: https://github.com/tummychow/git-absorb/archive/${{ version }}.tar.gz
  sha256: a0f74e6306d7fbd746d2b4a6856621d46a7f82e3e88b6bb8b6fc0480cf811f53

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - git-absorb --help

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Automatic git commit --fixup
  homepage: https://github.com/tummychow/git-absorb
  repository: https://github.com/tummychow/git-absorb

extra:
  recipe-maintainers:
    - danielnachun
